services:
  - type: web
    name: todo-flask-api
    env: python
    buildCommand: ls -l backend/ && pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    autoDeploy: true